# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
