# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 02:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rrule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrule_freq', models.CharField(blank=True, choices=[('WEEKLY', 'Every Week'), ('MONTHLY', 'Every Month')], max_length=10)),
                ('rrule_until', models.DateField(blank=True, null=True)),
                ('rrule_byday', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=3), size=None)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='recurrence',
            new_name='recurring',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rrule_byday',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rrule_freq',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rrule_until',
        ),
        migrations.AddField(
            model_name='rrule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
