# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='htmlLink',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
