# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='summary',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
