# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160406_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rrule',
            old_name='rrule_byday',
            new_name='byday',
        ),
        migrations.RenameField(
            model_name='rrule',
            old_name='rrule_freq',
            new_name='freq',
        ),
        migrations.RenameField(
            model_name='rrule',
            old_name='rrule_until',
            new_name='until',
        ),
    ]
