# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_calendar_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='color',
        ),
    ]
