# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_calendar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='color',
            field=models.CharField(default='%23CC3333', editable=False, max_length=12),
        ),
    ]
