# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20160406_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='rrule',
            name='count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
