# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20160410_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gcal_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
