# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rrule_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='rrule',
            name='exdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rrule',
            name='rdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
